sudo: required
services:
  - docker

before_install:
  - docker build -t tcscheurer/automated-deploy-app -f Dockerfile.dev .

script:
  - docker run tcscheurer/automated-deploy-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "automated-deploy-app"
  env: "AutomatedDeployApp-env"
  bucket_name: "elasticbeanstalk-us-east-2-591556832679"
  bucket_path: "automated-deploy-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
