FROM node:alpine

WORKDIR '/app'

COPY package.json ./
RUN npm install

# truthfully this COPY statement below isn't needed since we are using volumes in this case (dev)
# to point back to the local file system for our source files
COPY ./ ./

CMD ["npm","run","start"]

